# docker-compose.yml
services:
  omnihrdb:
    image: mysql:8.0
    container_name: omnihrdb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omnihrdb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - omnihr-net

  omnihr:
    build:
      context: ./omnihr-service
      dockerfile: Dockerfile
    image: truongthuanr/omnihr:latest
    container_name: omnihr-service
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./omnihr-service/configs/customconfig.json:/configs/config.json
    environment:
      CONFIG_PATH: /configs/config.json
      DB_HOST: omnihrdb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: omnihrdb
    networks:
      - omnihr-net

volumes:
  db_data:

networks:
  omnihr-net:
    external: true
